export const config = {
  spaces: true,
  indentation: 2,
  directory: './models',
  additional: {},
  dialect: 'mysql',
  port: 3306,
  host: '127.0.0.1',
  database: 'nba',
  storage: 'nba',
  tables: null,
  skipTables: null,
  skipFields: null,
  pkSuffixes: null,
  lang: 'es5',
  caseModel: 'o',
  caseFile: 'o',
  caseProp: 'c',
  noAlias: false,
  noInitModels: false,
  noWrite: false,
  views: false,
  singularize: false,
  password: 'root',
  username: 'root',
  useDefine: true,
  noIndexes: false,
};
